### ISSUE TITLE
There are multiple scalar report buttons

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#322] opened 2022-09-29 07:34 UTC
We really only need one, since we're inputting a number. Users are confused which one they have to press, and if they have to do it multiple times.

**Comment by maltekliemann** [comment] 2023-07-02 11:36
Bumping this

**Comment by Robiquet** [comment] 2023-08-11 14:14
duplicate of https://github.com/zeitgeistpm/ui/issues/1513

**Closed by Robiquet** 2023-08-11 14:14 UTC
Labels: bug, cosmetic, design
