### ISSUE TITLE
Confirmation message displaying ZTG instead of DOT

### ISSUE THREAD

**Issue by Boibit** [zeitgeistpm/ui#1517] opened 2023-07-07 13:36 UTC
Copy paste from submission in chaosdao.
![image](https://github.com/zeitgeistpm/ui/assets/61936910/edd5997f-0769-4e48-845c-ec9141ce957e)

**Comment by Robiquet** [comment] 2023-07-07 13:38
Duplicate of https://github.com/zeitgeistpm/ui/issues/1380

**Closed by Robiquet** 2023-07-07 13:38 UTC
