### ISSUE TITLE
Can't tell if proposed market is scalar or categorical

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#313] opened 2022-09-23 13:02 UTC
When looking at a proposed market, I can't tell if the market is scalar, or if someone's just messing with us by proposing a categorical market with outcome tokens LONG and SHORT.

**Comment by TvrtkoM** [comment] 2022-09-26 12:59
duplicate of #298

**Comment by mk26071980** [comment] 2023-02-06 13:03
I believe new cards design should solve that. 

![Image](https://user-images.githubusercontent.com/80706590/216978326-369d50ed-2c5d-458a-bc10-81a3e3c4ca3b.png)

**Comment by maltekliemann** [comment] 2023-02-06 13:12
@mk26071980 That looks like a card for a proposed market that's already approved. How does the card look like before approval?

**Comment by mk26071980** [comment] 2023-02-10 13:50
![Image](https://user-images.githubusercontent.com/80706590/218108165-7b883774-54dc-4e7f-9a3c-df1d1e44c3f1.png)

**Closed** 2023-03-02 12:07 UTC
Labels: bug, critical
