### ISSUE TITLE
Withdrawing most of the liquidity causes 24h change to go crazy

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#538] opened 2022-12-21 21:53 UTC
I removed about 99% of the liquidity from this market, and go the following result:

<img width="1920" alt="Screenshot 2022-12-21 at 18 35 45" src="https://user-images.githubusercontent.com/49552287/209008932-2d9a3d68-1ffe-4e64-8db1-8363d34a590d.png">

The 24h change should not be influenced by `pool_exit` calls, as it leaves prices unchanged, and no asset should be able decrease by more than 100% in any situation.

**Comment by maltekliemann** [comment] 2022-12-21 22:04
Here's another pool that I've removed liquidity from. The 400% increase of YES probably didn't happen either.

<img width="1920" alt="Screenshot 2022-12-21 at 23 02 58" src="https://user-images.githubusercontent.com/49552287/209010898-4b28df6e-82b1-4f6e-b14b-77a0f29f85e6.png">

**Comment by Robiquet** [comment] 2023-01-11 11:11
Tried reproduce this buy creating a market, making a trade then withdrawing most 90%+ of the liquidity.
Seems to be ok (market 539 on battery station):
<img width="795" alt="image" src="https://user-images.githubusercontent.com/4950844/211791706-bf2eafc5-8970-4746-ae3a-06229c2d9688.png">

@mk26071980  Let me know if you see this issue again and I'll investigate promptly

**Comment by lsaether** [comment] 2023-02-06 16:44
We're closing this because we weren't able to reproduce. Please re-open if it happens again @maltekliemann

**Closed by lsaether** 2023-02-06 16:44 UTC
Labels: t:bug
