### ISSUE TITLE
The Sign transaction button is still clickable, and will still sign the buy/sell transaction from the removed dialog.

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/ui#58] opened 2021-10-18 11:54 UTC
In a market, open the Buy or Sell dialog for a token, enter a number so that the Sign transaction key becomes clickable. Don't sign the transaction. Then remove the dialog. The Sign transaction button is still clickable, and will still sign the buy/sell transaction from the removed dialog.

OP:
![image](https://user-images.githubusercontent.com/25539605/137725339-9448da84-d5f5-41cc-a47f-1e68ff8368ce.png)

**Comment by yornaath** [comment] 2022-06-09 12:48
@lsaether I cant reproduce this bug either, can you or should we close it for now?

**Closed** 2022-07-10 18:11 UTC
Labels: s:proposed-for-sprint, t:bug
